apiVersion: v1
kind: Pod
  
metadata:
  name: pv-demo
  labels:
    app: pv-demo

spec: 
  containers:
    - name: express
      image: pvc-test:latest
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: data-volume
          mountPath: /data
            
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: demo-pvc