apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
  
metadata:
  name: bind-pod-reader
  namespace: default
    
subjects:
  - kind: ServiceAccount
    name: sa-reader
    namespace: default
      
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io